     // <![CDATA[
document.writeln('			<ul class="menusm" id="menu-top-menu">');
document.writeln('              <li><a href="index.html"><span>Home</span></a>');
document.writeln('                <ul>');
document.writeln('                  <li><a href="AboutROA.html "><span>About R.O.A.</span></a></li>');
document.writeln('                  <li><a href="AboutROA.html"><span>Terms Of Use</span></a></li>');
document.writeln('                  <li><a href="AboutROA.html"><span>Site Map</span></a></li>');
document.writeln('                </ul>');
document.writeln('              </li>');

document.writeln('  <li><a href="#" class="menu_navigation"><span>Features</span></a>');
document.writeln('    <ul>');
document.writeln('  <li><a href="#" class="menu_navigation"><span>Exclusive Interviews</span></a>');
document.writeln('    <ul>');
document.writeln('      <li><a href="_1Features_exclusiveinterviewsAtoL.html" class="menu_navigation"><span>A to L</span></a></li>');
document.writeln('      <li><a href="_1Features_exclusiveinterviewsMtoZ.html" class="menu_navigation"><span>M to Z</span></a></li>');
document.writeln('    </ul>');
document.writeln('  </li>');
document.writeln('      <li><a href="_1Features_latestnews.html" class="menu_navigation"><span>Latest News</span></a></li>');
document.writeln('      <li><a href="_1Features_TourDates.html" class="menu_navigation"><span>Tour Dates</span></a></li>');
document.writeln('      <li><a href="_1Features_BandPortfolio.html" class="menu_navigation"><span>Band Porfolios</span></a></li>');
document.writeln('      <li><a href="_1Features_videovault.html" class="menu_navigation"><span>Video Vault</span></a></li>');
document.writeln('      <li><a href="AudienceParticipation.html" class="menu_navigation"><span>Audience Participation</span></a></li>');
document.writeln('      <li><a href="_1Features_backstagegreenroom.html" class="menu_navigation"><span>Backstage / Greenroom</span></a></li>');
document.writeln('      <li><a href="_1Features_vipredcarpet.html" class="menu_navigation"><span>VIP / Red Carpet</span></a></li>');
document.writeln('      <li><a href="Commentary.html" class="menu_navigation"><span>Commentary</span></a></li>');
document.writeln('      <li><a href="http://www.rockoveramerica.com/Archives/index.php" class="menu_navigation"><span>Archives </span></a></li>');
document.writeln('    </ul>');
document.writeln('  </li>');

document.writeln('  <li><a href="#" class="menu_navigation"><span>Multi-Media Links</span></a>');
document.writeln('    <ul>');
document.writeln('  <li><a href="" class="menu_navigation"><span>R.O.A.Live</span></a>');
document.writeln('    <ul>');
document.writeln('      <li><a href="_1MultiMediaLinks_ROALive__AboutROALive.html" class="menu_navigation"><span>About ROA LIVE</span></a></li>');
document.writeln('      <li><a href="https://www.youtube.com/channel/UC3pix05FDQJ0Cu9PxELQBhw" class="menu_navigation"><span>R.O.A. YouTube Link</span></a></li>');
document.writeln('      <li><a href="https://soundcloud.com/rockoveramerica" class="menu_navigation"><span>R.O.A. SoundCloud</span></a></li>');
document.writeln('    </ul>');
document.writeln('  </li>');
document.writeln('  <li><a href="#" class="menu_navigation"><span>Share MP3</span></a>');
document.writeln('    <ul>');
document.writeln('  <li><a href="" target="_blank" class="menu_navigation"><span>MP3 Share Links</span></a>');
document.writeln('    <ul>');
document.writeln('      <li><a href="https://www.reverbnation.com/" target="_blank" class="menu_navigation"><span>Reverb Nation</span></a></li>');
document.writeln('      <li><a href="http://www.tunecore.com" target="_blank" class="menu_navigation"><span>Tunecore</span></a></li>');
document.writeln('      <li><a href="https://www.myspace.com/" target="_blank" class="menu_navigation"><span>MySpace</span></a></li>');
document.writeln('      <li><a href="http://www.jamendo.com" target="_blank" class="menu_navigation"><span>Jamendo.com</span></a></li>');
document.writeln('      <li><a href="http://www.bandcamp.com" target="_blank" class="menu_navigation"><span>Band Camp</span></a></li>');
document.writeln('      <li><a href="https://www.last.fm/" target="_blank" class="menu_navigation"><span>Last FM</span></a></li>');
document.writeln('    </ul>');
document.writeln('  </li>');
document.writeln('      <li><a href="http://www.facebook.com/rockofamerica/" target="_blank" class="menu_navigation"><span>R.O.A. Facebook</span></a></li>');
document.writeln('      <li><a href="http://www.twitter.com/rockoveramerica" target="_blank" class="menu_navigation"><span>R.O.A. Twitter</span></a></li>');
document.writeln('    </ul>');
document.writeln('  </li>');

document.writeln('    </ul>');
document.writeln('  </li>');
document.writeln('  <li><a href="#" class="menu_navigation"><span>Latest Reviews</span></a>');
document.writeln('    <ul>');
document.writeln('  <li><a href="#" class="menu_navigation"><span>Music Reviews</span></a>');
document.writeln('    <ul>');
document.writeln('      <li><a href="_1Latestreviews_concertreviews.html" class="menu_navigation"><span>Concert Reviews</span></a></li>');
document.writeln('      <li><a href="_1Latestreviews_cdreviews.html" class="menu_navigation"><span>CD Reviews</span></a></li>');
document.writeln('    </ul>');
document.writeln('  </li>');
document.writeln('  <li><a href="#.html" class="menu_navigation"><span>Entertainment Reviews</span></a>');
document.writeln('    <ul>');
document.writeln('      <li><a href="_1Entertainmentreviews_moviereviews.html" class="menu_navigation"><span>Movie Reviews</span></a></li>');
document.writeln('      <li><a href="_1Entertainmentreviews_showreviews.html" class="menu_navigation"><span>Show Reviews</span></a></li>');
document.writeln('      <li><a href="_1Entertainmentreviews_attractionreviews.html" target="_blank" class="menu_navigation"><span>Attraction Reviews</span></a></li>');
document.writeln('    </ul>');
document.writeln('  </li>');
document.writeln('    </ul>');
document.writeln('  </li>');

document.writeln('  <li><a href="#" class="menu_navigation"><span>Travel</span></a>');
document.writeln('    <ul>');
document.writeln('      <li><a href="_1Travel_hotelandlodging.html" class="menu_navigation"><span>Hotels and Lodging</span></a></li>');
document.writeln('      <li><a href="_1Travel_restaurants.html" class="menu_navigation"><span>Restaurants</span></a></li>');
document.writeln('      <li><a href="_1Travel_attractions.html" class="menu_navigation"><span>Attractions</span></a></li>');
document.writeln('      <li><a href="_1Travel_traveldestination.html" target="_blank" class="menu_navigation"><span>Travel Destinations</span></a></li>');
document.writeln('      <li><a href="_1Travel_cruises.html" class="menu_navigation"><span>Cruises</span></a></li>');
document.writeln('      <li><a href="_1Travel_planetrainauto.html" class="menu_navigation"><span>Plane, Train, Automobile</span></a></li>');
document.writeln('      <li><a href="_1Travel_artsandculture.html" class="menu_navigation"><span>Arts and Culture</span></a></li>');
document.writeln('      <li><a href="_1Travel_outdooradventure.html" class="menu_navigation"><span>Outdoor and Adventure</span></a></li>');
document.writeln('      <li><a href="_1Travel_amusementparks.html" class="menu_navigation"><span>Amusement Parks</span></a></li>');
document.writeln('      <li><a href="_1Travel_expeditionsandsiteseeing.html" class="menu_navigation"><span>Expeditions and Site Seeing</span></a></li>');
document.writeln('      <li><a href="_1Travel_beaches.html" target="_blank" class="menu_navigation"><span>Beaches</span></a></li>');
document.writeln('      <li><a href="_1Travel_boozetraveler.html" class="menu_navigation"><span>Booze Traveler</span></a></li>');
document.writeln('      <li><a href="_1Travel_golfcoursesdriving.html" class="menu_navigation"><span>Golf Courses and Driving Ranges</span></a></li>');
document.writeln('      <li><a href="_1Travel_coffeehouses.html" class="menu_navigation"><span>Cigar Bars, Coffee Houses, Dinners, Dives and Outdoor Cafes </span></a></li>');
document.writeln('    </ul>');
document.writeln('  </li>');

document.writeln('  <li><a href="contact.html" class="menu_navigation"><span>Contact</span></a></li>');
document.writeln('</ul>');
document.writeln('<div class="clr"></div>');

// ]]>